# Filename: travis.yml

language: cpp

sudo: required
dist: trusty

compiler:
    - clang
    - gcc

install:
    - sudo apt-get update --fix-missing
    - sudo apt-get install -y lcov

script:
    - cmake .
    - make -j2 do_test
#    - make pytest
